### ISSUE TITLE
Red Hat SSO fails to standup when deployed on Minishift with OC 3.7

### ISSUE THREAD

**Issue by geoand** [snowdrop/spring-boot-http-secured-booster#30]
When I issued

```bash
oc create -f service.sso.yaml
```

the Red Hat SSO server failed to stand up giving the following error:

```
12:57:42,488 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 53) WFLYSRV0010: Deployed “keycloak-server.war” (runtime-name : “keycloak-server.war”)
12:57:42,893 ERROR [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0055: Caught exception during boot: java.lang.IllegalStateException: WFLYCTL0056: Could not rename /opt/eap/standalone/configuration/standalone_xml_history/current to /opt/eap/standalone/configuration/standalone_xml_history/20180213-125742892
    at org.jboss.as.controller.persistence.ConfigurationFile.createHistoryDirectory(ConfigurationFile.java:638)
    at org.jboss.as.controller.persistence.ConfigurationFile.successfulBoot(ConfigurationFile.java:470)
    at org.jboss.as.controller.persistence.BackupXmlConfigurationPersister.successfulBoot(BackupXmlConfigurationPersister.java:94)
    at org.jboss.as.controller.AbstractControllerService.finishBoot(AbstractControllerService.java:451)
    at org.jboss.as.server.ServerService.boot(ServerService.java:373)
    at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:301)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by geoand** [comment]
Closing this the RHOAR documentation explicitly mentions that the CentOS base image needs to be used when deploying via Minishift (`--iso-url=centos` during the start of the image).
